AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
